-- M0: shared helpers + regions + trades taxonomy (reference data, all envs).
-- Column names here are contractual per spec §3 — extra columns are allowed,
-- renames are not.

-- Every table with updated_at uses this trigger.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- regions: fixed list for launch (spec locks radius/map search out of MVP).
-- Hierarchy via parent_id; Tobago exists but is disabled until expansion.
-- ---------------------------------------------------------------------------
create table public.regions (
  id int primary key,
  name text not null,
  parent_id int references public.regions (id),
  enabled boolean not null default true,
  sort int not null default 0,
  created_at timestamptz not null default now()
);

insert into public.regions (id, name, parent_id, enabled, sort) values
  (1,  'Trinidad', null, true,  1),
  (2,  'Tobago',   null, false, 2),
  -- Trinidad regions (spec M0.3), alphabetical
  (10, 'Arima',                      1, true, 10),
  (11, 'Chaguanas',                  1, true, 11),
  (12, 'Couva–Tabaquite–Talparo',    1, true, 12),
  (13, 'Diego Martin',               1, true, 13),
  (14, 'Mayaro–Rio Claro',           1, true, 14),
  (15, 'Penal–Debe',                 1, true, 15),
  (16, 'Point Fortin',               1, true, 16),
  (17, 'Port of Spain',              1, true, 17),
  (18, 'Princes Town',               1, true, 18),
  (19, 'San Fernando',               1, true, 19),
  (20, 'San Juan–Laventille',        1, true, 20),
  (21, 'Sangre Grande',              1, true, 21),
  (22, 'Siparia',                    1, true, 22),
  (23, 'Tunapuna–Piarco',            1, true, 23);

-- ---------------------------------------------------------------------------
-- trades: seeded taxonomy + user-proposed entries (M2) + admin merge (M9).
-- keywords feed search synonyms ("ac" → AC Technician) per M3.
-- Seeded ids start at 100; proposed trades get ids from this sequence too.
-- ---------------------------------------------------------------------------
create table public.trades (
  id int generated by default as identity (start with 1000) primary key,
  slug text unique not null,
  name text not null,
  category text not null,
  keywords text[] not null default '{}',
  status text not null default 'active'
    check (status in ('active', 'proposed', 'merged')),
  merged_into_id int references public.trades (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trades_updated_at
  before update on public.trades
  for each row execute function public.set_updated_at();

insert into public.trades (id, slug, name, category, keywords) values
  -- Home & Building
  (100, 'plumber',            'Plumber',                'Home & Building', '{pipes,leak,toilet,sink,water pump,tank}'),
  (101, 'electrician',        'Electrician',            'Home & Building', '{wiring,breaker,lights,inspection,current}'),
  (102, 'mason',              'Mason',                  'Home & Building', '{brick,block,concrete,plaster,foundation}'),
  (103, 'carpenter',          'Carpenter',              'Home & Building', '{wood,cupboard,furniture,doors,shelves}'),
  (104, 'painter',            'Painter',                'Home & Building', '{painting,paint,interior,exterior}'),
  (105, 'roofer',             'Roofer',                 'Home & Building', '{roof,galvanize,leak,gutter,ceiling}'),
  (106, 'tiler',              'Tiler',                  'Home & Building', '{tiles,tiling,floor,porcelain,ceramic}'),
  (107, 'welder',             'Welder',                 'Home & Building', '{welding,gate,grill,burglar proof,steel}'),
  (108, 'ac-technician',      'AC Technician',          'Home & Building', '{ac,a/c,air condition,air conditioning,aircon,refrigeration,fridge}'),
  (109, 'appliance-repair',   'Appliance Repair',       'Home & Building', '{washing machine,dryer,stove,oven,microwave,fridge}'),
  (110, 'pest-control',       'Pest Control',           'Home & Building', '{exterminator,termites,rats,roaches,fumigation}'),
  (111, 'landscaper',         'Landscaper & Gardener',  'Home & Building', '{garden,lawn,yard,cutlass,bush,trimming,plants}'),
  (112, 'pool-cleaning',      'Pool Cleaning',          'Home & Building', '{pool,swimming pool,pool maintenance}'),
  (113, 'sprinkler-systems',  'Sprinkler Systems',      'Home & Building', '{irrigation,sprinklers,watering}'),
  (114, 'fencing',            'Fencing',                'Home & Building', '{fence,chain link,wall,boundary}'),
  (115, 'locksmith',          'Locksmith',              'Home & Building', '{locks,keys,lockout,safe}'),
  (116, 'handyman',           'Handyman',               'Home & Building', '{odd jobs,repairs,fix,maintenance}'),
  (117, 'gypsum-drywall',     'Gypsum & Drywall',       'Home & Building', '{sheetrock,partition,false ceiling,drywall}'),
  (118, 'glass-aluminium',    'Glass & Aluminium',      'Home & Building', '{windows,sliding door,shower door,mirrors}'),
  (119, 'curtains-blinds',    'Curtains & Blinds',      'Home & Building', '{drapes,upholstery,blinds}'),
  (120, 'water-tank-services','Water Tank Services',    'Home & Building', '{tank cleaning,water tank,pressure washing}'),
  (121, 'septic-services',    'Septic Services',        'Home & Building', '{cesspit,soakaway,sewer,waste}'),
  (122, 'moving-hauling',     'Moving & Hauling',       'Home & Building', '{movers,transport,truck,delivery,junk removal}'),
  (123, 'contractor',         'Construction Contractor','Home & Building', '{builder,renovation,extension,construction}'),
  (124, 'interior-decorator', 'Interior Decorator',     'Home & Building', '{decor,design,staging,furnishing}'),

  -- Auto
  (200, 'mechanic',           'Mechanic',               'Auto', '{car repair,engine,brakes,suspension,service}'),
  (201, 'car-detailing',      'Car Wash & Detailing',   'Auto', '{car wash,detailing,polish,shampoo,valet}'),
  (202, 'auto-electrician',   'Auto Electrician',       'Auto', '{car electrical,starter,alternator,wiring}'),
  (203, 'tyre-shop',          'Tyre Shop',              'Auto', '{tire,tires,tyres,wheel alignment,balancing,rims}'),
  (204, 'auto-body',          'Auto Body & Paint',      'Auto', '{body work,spray,dent,accident,rust}'),
  (205, 'auto-ac',            'Auto AC',                'Auto', '{car ac,car air condition,freon}'),
  (206, 'windscreen-repair',  'Windscreen Repair',      'Auto', '{windshield,glass,chip,crack}'),
  (207, 'car-audio-alarms',   'Car Audio & Alarms',     'Auto', '{sound system,speakers,alarm,tint,dashcam}'),
  (208, 'towing',             'Towing & Wrecker',       'Auto', '{wrecker,tow truck,breakdown,flatbed}'),

  -- Personal & Home services
  (300, 'babysitting',        'Babysitting',            'Personal & Home', '{childcare,nanny,babysitter}'),
  (301, 'housekeeping',       'Housekeeping',           'Personal & Home', '{cleaning,maid,domestic,deep clean}'),
  (302, 'catering',           'Cook & Catering',        'Personal & Home', '{food,meals,cook,chef,pelau,roti}'),
  (303, 'hair-beauty',        'Hair & Beauty',          'Personal & Home', '{hairdresser,salon,braids,weave,styling}'),
  (304, 'barber',             'Barber',                 'Personal & Home', '{haircut,trim,fade,lineup}'),
  (305, 'nails',              'Nail Technician',        'Personal & Home', '{manicure,pedicure,acrylic,gel}'),
  (306, 'makeup-artist',      'Makeup Artist',          'Personal & Home', '{mua,makeup,bridal makeup}'),
  (307, 'tailoring',          'Tailoring & Seamstress', 'Personal & Home', '{sewing,alterations,dressmaker,hemming}'),
  (308, 'laundry-ironing',    'Laundry & Ironing',      'Personal & Home', '{washing,pressing,dry cleaning}'),
  (309, 'elder-care',         'Elder Care',             'Personal & Home', '{caregiver,geriatric,home care,nursing}'),
  (310, 'pet-grooming',       'Pet Grooming & Care',    'Personal & Home', '{dog grooming,pet sitting,dog walking,vet assistant}'),
  (311, 'fitness-trainer',    'Fitness Trainer',        'Personal & Home', '{personal trainer,gym,exercise,coach}'),
  (312, 'massage-therapist',  'Massage Therapist',      'Personal & Home', '{massage,spa,physio,therapy}'),

  -- Tuition
  (400, 'maths-tuition',      'Maths Lessons',          'Tuition', '{mathematics,math,add maths,csec maths}'),
  (401, 'english-tuition',    'English Lessons',        'Tuition', '{english,literature,essay,csec english}'),
  (402, 'chemistry-tuition',  'Chemistry Lessons',      'Tuition', '{chemistry,csec chemistry,cape chemistry}'),
  (403, 'physics-tuition',    'Physics Lessons',        'Tuition', '{physics,csec physics,cape physics}'),
  (404, 'spanish-tuition',    'Spanish Lessons',        'Tuition', '{spanish,language}'),
  (405, 'sea-prep',           'SEA Preparation',        'Tuition', '{sea,secondary entrance,common entrance,exam prep}'),
  (406, 'music-lessons',      'Music Lessons',          'Tuition', '{piano,guitar,pan,steelpan,drums,voice,singing}'),
  (407, 'it-tutoring',        'Computer & IT Tutoring', 'Tuition', '{computer lessons,coding,typing,it}'),
  (408, 'swimming-lessons',   'Swimming Lessons',       'Tuition', '{swim,swimming,lessons}'),

  -- Events
  (500, 'photographer',       'Photographer',           'Events', '{photos,photoshoot,wedding photos,portraits}'),
  (501, 'videographer',       'Videographer',           'Events', '{video,film,drone,editing}'),
  (502, 'dj',                 'DJ',                     'Events', '{music,party,fete,sound}'),
  (503, 'event-planning',     'Event Planning',         'Events', '{planner,coordinator,wedding planner,party planning}'),
  (504, 'cakes-pastries',     'Cakes & Pastries',       'Events', '{cake,baker,cupcakes,wedding cake,pastry}'),
  (505, 'decor-rentals',      'Decor & Rentals',        'Events', '{decorations,tents,chairs,tables,balloons}'),
  (506, 'sound-lighting',     'Sound & Lighting',       'Events', '{pa system,speakers,stage,lights}'),
  (507, 'mc-host',            'MC & Host',              'Events', '{emcee,master of ceremonies,host}'),
  (508, 'bartending',         'Bartending',             'Events', '{bar,drinks,cocktails,mobile bar}'),

  -- Tech & Office
  (600, 'computer-repair',    'Computer Repair',        'Tech & Office', '{laptop,pc,virus,upgrade,data recovery}'),
  (601, 'phone-repair',       'Phone Repair',           'Tech & Office', '{screen,battery,iphone,samsung,unlock}'),
  (602, 'web-graphic-design', 'Web & Graphic Design',   'Tech & Office', '{website,logo,branding,flyers,social media}'),
  (603, 'cctv-security',      'CCTV & Security Systems','Tech & Office', '{cameras,surveillance,alarm,access control}'),
  (604, 'networking-wifi',    'Networking & WiFi',      'Tech & Office', '{internet,router,network,cabling}'),
  (605, 'printing-signage',   'Printing & Signage',     'Tech & Office', '{banners,signs,business cards,tshirts,embroidery}'),
  (606, 'accounting',         'Accounting & Bookkeeping','Tech & Office','{accounts,taxes,vat,payroll,bookkeeper}');

-- Reference data is world-readable (logged-out browse, spec M3).
alter table public.regions enable row level security;
alter table public.trades enable row level security;

create policy "regions are public" on public.regions
  for select using (true);

create policy "trades are public" on public.trades
  for select using (true);

-- New tables are NOT auto-exposed to API roles (post-2026 Supabase default),
-- so every migration grants explicitly. Writes to taxonomy are edge-function
-- (service role) territory only.
grant select on public.regions to anon, authenticated;
grant select on public.trades to anon, authenticated;
grant all on public.regions, public.trades to service_role;
grant usage, select on all sequences in schema public to service_role;
